# fly.toml file generated for catfood-app on 2023-01-19T16:44:37-07:00

app = "catfood-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "registry.fly.io/catfood-app:latest"

[deploy]
  release_command = "java -jar app.jar migrate"

[env]
  REDIS_URL = "redis://fly-catfood-redis.upstash.io:6379"
  DB_MIGRATION_URL = "jdbc:postgresql://catfood-db.flycast:5432/catfood_app?sslmode=disable"
  DB_APP_URL = "r2dbc:pool:postgresql://catfood-db.flycast:5432/catfood_app?maxIdleTime=PT60S"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
