FROM ghcr.io/aaomidi/certbot-dns-google-domains:latest

# install flyctl

# Copy deploy script to /etc/letsencrypt/renewal-hooks/deploy
# Copy google domains config to '/var/lib/letsencrypt/dns_google_domains_credentials.ini'

