ktor:
  development: "$DEVELOPMENT:false"
  deployment:
    port: 8080
  application:
    modules:
      - dog.catfood.ApplicationKt.main

db:
  migration:
    url: "$DB_MIGRATION_URL"
    user: "$DB_MIGRATION_USER"
    password: "$DB_MIGRATION_PASSWORD"
  app:
    url: "$DB_APP_URL"
    user: "$DB_APP_USER"
    password: "$DB_APP_PASSWORD"

redis:
  url: "$REDIS_URL"
  password: "$REDIS_PASSWORD"

ca:
  certificate: "$CA_CERTIFICATE"
  key: "$CA_KEY"
  password: "$CA_PASSWORD"
