ktor:
  development: "$DEVELOPMENT:false"
  deployment:
    port: 8080
  application:
    modules:
      - dog.catfood.ApplicationKt.main

db:
  host: "$DB_HOST"
  port: "$DB_PORT"
  name: "$DB_NAME"
  user: "$DB_USER"
  password: "$DB_PASSWORD"

redis:
  url: "$REDIS_URL"
  password: "$REDIS_PASSWORD"

ca:
  certificate: "$CA_CERTIFICATE"
  key: "$CA_KEY"
  password: "$CA_PASSWORD"
