# fly.toml file generated for catfood-proxy on 2023-03-22T09:59:40-06:00

app = "catfood-proxy"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "den"
processes = []

[build]
  image = "registry.fly.io/catfood-proxy:latest"

[env]
  CATFOOD_URL = "http://catfood-app.flycast:8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 443
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
